services:
  - type: web
    name: portfolio-app
    env: python
    repo: https://github.com/AliceYangAC/AliceYangFolio
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
