name: Keepalive Ping

on:
  schedule:
    - cron: "5-59/10 * * * *" # Every 10 minutes
  workflow_dispatch: # Manual trigger option

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ping script
        run: python ping.py
